### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by HappyLife-together** [tchambon/deepfrench#1]
RuntimeError: you can only change requires_grad flags of leaf variables. If you want to use a computed variable in a subgraph that doesn't require differentiation use var_no_grad = var.detach().

**Comment by tcnguyen** [comment]
I had the same error on running "learn = language_model_learner(data_lm, pretrained_fnames=pretained_data, drop_mult=0)"

**Comment by tcnguyen** [comment]
In fact I just figured out that I did not install the pytorch v1 (in preview) 

pip install torch_nightly -f https://download.pytorch.org/whl/nightly/cu92/torch_nightly.html

**Comment by HappyLife-together** [comment]
thank you
