### ISSUE TITLE
Fastai API change

### ISSUE THREAD

**Issue by brunosez** [tchambon/deepfrench#4]
Note when loading pre-trained you must add arch argument
learn = language_model_learner(data_lm,arch=AWD_LSTM, pretrained_fnames=pretained_data, drop_mult=0)

**Comment by koper921** [comment]
> learn = language_model_learner(data_lm,arch=AWD_LSTM, pretrained_fnames=pretained_data, drop_mult=0)

Thank's do you got this error when you lauch this line ?

RuntimeError: you can only change requires_grad flags of leaf variables. If you want to use a computed variable in a subgraph that doesn't require differentiation use var_no_grad = var.detach().

![image](https://user-images.githubusercontent.com/38080730/54076581-9c442d80-42ad-11e9-8ff1-200484a29b77.png)

**Comment by brunosez** [comment]
Hi ,
I don't remember exactly, with the new syntax it doesn't complaint.
Finally I completely give up on fastai V1, last week I've reproduced imdb
notebook on fastai v07, with around 30h of compute
 on a P4000 instance on the cloud. Locally with only 1060 nvidia card 4go
it's useless
Will keep you informed if I succeeded in training with deepfrench
Rgds
Bruno

**Comment by koper921** [comment]
Hi thanks, I have just try the classifier (without training it ) and I have only obtain 0.58 in accuracy on the validation set with this dataset  task1 : https://gitlia.univ-avignon.fr/rouvierm/deft-2017/tree/master/data, maybe I have done something bad

**Comment by brunosez** [comment]
Hi,
You must retrain the classifier, first with freezing all layers except the laston , and second with unfreeze of several layers as in imdb notebook !
May be it can work directly , if you have exactly the same target class ?
Rgds
Bruno

**Comment by koper921** [comment]
Ok thanks,
 I thought it was possible to directly fine tunning the model with  french dataset sentiment analysis with (4 classes : neutral, positive, negative, and mixed  of 900 sentences) and retrain the last layes  like in the notebook classifcation example  in the part classification task , or maybe i'm wrong ?

And when I've done this results are not so good, maybe if i had unlabelled data for fine tunning it can improve the results.
Did you obtain good results on french dataset without retrain it from scratch  and with different number of classes ? 

Cédric

**Comment by tchambon** [comment]
Hello,
I will update deepfrench this week to take into account the new fastai API. 
@brunosez there has been some breaking change in fastai on the import functions, so you cannot import the Deep French weights directly. I will include the code to import the weights on the last version of fastai.

@koper921, you must do some fine tuning on your classification task. You can follow the process here: https://github.com/tchambon/deepfrench/blob/master/ULMFit%20Classifier%20example.ipynb
The LM model doesn't include the classification layer so if you don't train it, it will just be random guessing.

**Comment by brunosez** [comment]
Thanks Thomas
for new fastAI, it's that I guessed finally when I failed to transfer
learning the classification

For koper921, you must follow also imdb method, with learning rate finder,
and ajust nb epoch...

may be the Mooc fast ai part2 will give the correct process

Rgds
Bruno

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Le lun. 11 mars 2019 à 17:06, Thomas Chambon <notifications@github.com> a
écrit :

**Comment by koper921** [comment]
Yes i have fine tuned  the model like in the notebook https://github.com/tchambon/deepfrench/blob/master/ULMFit%20Classifier%20example.ipynb

And after i train it like in the part 'classification task'  of the Classifier example notebook it is not sufficient ?
here :
<img width="908" alt="Capture d’écran 2019-03-11 à 17 34 01" src="https://user-images.githubusercontent.com/38080730/54140625-53fb4b80-4424-11e9-96b9-83b15e50375e.png">

**Comment by brunosez** [comment]
For tuning, I think of more detailed process like
 in v3 lesson3-imdb notebook
https://github.com/fastai/course-v3/blob/master/nbs/dl1/lesson3-imdb.ipynb
Rgds
Bruno

**Comment by tchambon** [comment]
I have updated the classification example taking into account the new fastai API. I have tested it and it worked with the old weights.

For the LM training example, I have not updated it yet because I would like to train it from scratch to test a little change and it takes some GPU time. I will do it soon.

I am closing this issue for now. If it does not work for you, please update it with the error message.

**Comment by brunosez** [comment]
Thanks , OK for the learner ,
I've always an issue at the beginning ?
data_lm = TextLMDataBunch.load(PATH_LM, 'data_lm', bs=64)

NotADirectoryError: [Errno 20] Not a directory: 'data/class/lm/data_lm/itos.pkl'
