### ISSUE TITLE
Add vocabulary

### ISSUE THREAD

**Issue by Shiro-LK** [tchambon/deepfrench#5]
Hi,

Thank for the repository, it helps to understand how train our own classifier.
I have a question, is it possible to increase the vocabulary of the model without training from scratch again ? 

Thanks !

**Comment by tchambon** [comment]
Hi,

I guess you can follow the fine-tuning approach (like the movie review dataset) with a bigger vocab, to benefit from the pre-training with the smaller vocab (new vocab will be initialized with the mean of the embeddings).
I am planning to retrain soon the model with a bigger vocab and some new tricks.
Why do you want a bigger vocab and of what size?

**Comment by Shiro-LK** [comment]
Hi, 
thanks for your answer.
The data I am trying to use is a medical dataset, so there are few important words which are sometimes not present in the original vocab of the model. That's why I was wondering if it is possible to increase it. I did not count  but I suppose I need an increasing of few hundred words only.
If I use a different value of "max_vocab" parameters for the TextLMDataBunch function during fine tuning, will it increase the vocabulary ?

**Comment by tchambon** [comment]
This is not how it is working.

When you use the pretrained model on new data, it will tokenize your data et check it against the vocab of the pretrained model. For each word, if the word is in the source vocab, the model will use the learned embedding.
If there is a new word, it will be added in your vocab (for the N most used words, N being the size of vocab you specify). For this, the library creates a new embedding which is initialized with the mean value of all embeddings. 

So this should work for your need. You only have to specify your max vocab size, and the N most common words will be in your new vocab.
