### ISSUE TITLE
Dataset for classification training

### ISSUE THREAD

**Issue by VinceBro** [tchambon/deepfrench#6]
Hi I am currently trying to train a model for french language by inspiring myself of what you did, but I don't understand where you got your data for the classification part of the training. I have looked all over the internet and haven't been able to find some labeled quality data for sentiment analysis (I found translation of twitter reviews which were really bad but that is the best I found). I saw in your README that you used data from a french IMDb like website, would you mind specifying what website you used?

**Comment by tchambon** [comment]
Hi.
I downloaded data from a famous french movie review website (using web scraping).
However, I cannot release the data as it's not allowed by the website ToS.
